### ISSUE TITLE
Pathways listing other pathways

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#101]
Currently when you visit a pathway, the left sidebar will contain only the 3 standard buttons plus, right above them, a link to the current pathway. I believe that section would be more useful if it simply listed all the pathways and indicated which one was currently selected. This would be the same behavior of standard pages where sibling items are shown and the current page is highlighted.

**Comment by joelworsham** [comment]
@banksashleym All set.

I've added a new widget called "List Posts". You can add this to the pathway's sidebars and then select "Pathway" for the post type to use. This will provide a list of all Pathways.

**Comment by banksashleym** [comment]
Good deal, thanks!
I'm dumb...could you give a quick explanation on how to add the widget to the pathway sidebar? 

Thanks!

**Comment by joelworsham** [comment]
Ha no worries.

Actually, as I'm looking more, I remembered that Pathways do not belong to site sections, so they don't actually have their own sidebars... I will need to adjust this slightly to make this work out better.

**Comment by joelworsham** [comment]
I added the pathway list to pathway pages in the sidebar automatically now. I'll leave in the post list widget just in case it comes in handy.

Let me know if this is what you're looking for.
