### ISSUE TITLE
Gravity Forms not showing up on certain pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#106]
I have been e-mailing the necessary people about the new process for forms. When i go to send the link, some of the forms are not populating at all?

Forms not showing up:
Federal Direct Loan Form:
http://jacksoncollege.staging.wpengine.com/financial-aid/loans/federal-direct-loan-request-form/

Campus View Applications:
http://jacksoncollege.staging.wpengine.com/campus-view-student-housing/apply-for-housing/housing-application/

Sponsor Application Form:
http://jacksoncollege.staging.wpengine.com/pei/sponsor-application/

The should all be linked correctly, so I'm not sure what's going on?

Also, I'm not sure that the plugin is working correctly because now I can't go in and update a form.

Thanks!

**Comment by joelworsham** [comment]
This was caused by the "redirect issue" that I fixed (mentioned in the email)
