### ISSUE TITLE
Forms plugin question

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#111]
Just had a question specifically about jobs for jets...On the forms plugin I was able to add entries right in Wordpress instead of having to fill out the form online? Now when i click on "entries" it defaults to the Campus Tour Central Campus form for entries.

Thanks!

**Comment by banksashleym** [comment]
Omg, I'm so dumb...it's been a long week lol. Never mind, I was trying to add the jobs into forms instead of the jobs for jets plugin...DUH!

**Comment by joelworsham** [comment]
Haha, no worries! I know how that goes.
