### ISSUE TITLE
"courses" tab in side nav that would pull defined set of courses

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#112]
This keeps slipping my mind to ask about, and this can wait until after we launch, but a few of the faculty members have asked that their courses be listed in their site section (and in the future I would like to list the courses for each program). We talked about doing a side nav link that would link to a page with a simple table that lists all of the say Biology classes. I would like this to function just like the degree page, where you are able to click on a class and the description would drop down beneath it.

If possible, I would like to be able to pick and choose which classes belong to a certain page. For instance with Biology, there are some classes that are still BIO classes but aren't technically listed in the courses as "BIO".

Thank you!

**Comment by brashrebel** [comment]
Is this a critical pre-launch enhancement?

**Comment by banksashleym** [comment]
No, this can wait. For those who have asked I created a courses page and just listed the courses there. It's like we have it now on our site so they will be satisfied with that.

Thanks!

**Comment by joelworsham** [comment]
@banksashleym 

So, let me know if this works.

I've added a shortcoded `[program_courses]`. You can already add courses to programs (on the right side of each program edit screen). So this shortcode will pull in any courses that belong to a program and display them in a table, like on the degree pages.

You use it by finding the ID of the program and using it in the shortcode like so: `[program_courses program="139"]`, where `139` will be the program ID you need to use.

You can create pages and add them to the site sections accordingly, then add this shortcode to them, and then finally link to them from the sidebar in a widget, whether that be from a button, a menu item, or a hard-link in the text widget.

**Comment by banksashleym** [comment]
Awesome, thank you, this is wonderful!!
Sorry to be a pain, but could we also put a parameter in that pulls specific courses not necessarily linked to a program? For instance, we have many developmental courses that aren't really tied to a specific program. Our Foundation Studies would like to include a list of developmental courses we offer.

Could we do something like [program_courses course="139, 140, 141"] where I could pull a specific range of courses?

Thanks!

**Comment by joelworsham** [comment]
Sure thing. I will add 2 more parameters `include` and `exclude`. These will work in conjunction with the `program` parameter or without.
