### ISSUE TITLE
breadcrumbs for academic program pages (not parent page)

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#113]
We don't need to worry about this before we launch, but thought it should be added to the list. 

When I'm on a program parent page (that pulls in the program information to the plugin) I like the way those breadcrumbs are set up with Home/Academics/Programs of Study/Program:Cardiac Sonography.

However when i navigate to one of the additional pages i've added the structure of the breadcrumbs changes a little to Home/Programs/Cardiac Sonography. i don't mind the actual structure, but when I click on the middle breadcrumb "Programs" I'm taken to a random list of programs that has the Jackson College News template. Could we link instead back to the programs of study boxes or the pathway for which that program belongs?

**Comment by joelworsham** [comment]
Ah yes I see. Sure thing.

**Comment by joelworsham** [comment]
This was definitely a bug. I believe it was a vestige of something else we had done before, but I couldn't pin it on what.
