### ISSUE TITLE
Search feature image and results

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#114]
Is there a way to set the search page feature image? It seems like it's pulling in the image of the first result :) I typed in "president" and got a kick out of that!

Also, would there be a reason why when you type in a word in some cases it will automatically go to a relevant page instead of returning a list of results? For instance, i wanted to search for our marketing department, but when I typed in "marketing" it went right to the marketing program page. 

Thanks!

**Comment by joelworsham** [comment]
Oh boy, you're right about that. Sorry for that! I'll get a way to do this ASAP.

**Comment by joelworsham** [comment]
And about the "marketing" thing, I think it's just another instance of WordPress "trying to be helpful". I'll see if this can be disabled.

**Comment by banksashleym** [comment]
Same thing with this as the 404 page, the image is still pulling images that populate the search results? I just want to double check that the president isn't going to find his huge picture up there when he searches for "president" (because I'm pretty sure he will lol :) Thank you so much!!

**Comment by joelworsham** [comment]
Ha right, same fix as with 404 which I just commented on.
