### ISSUE TITLE
Spotlight hero images only cycling through one time

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#115]
I just looked at the website and noticed that there is no hero/spotlight image present even though there are two spotlights that are starred? It's as if it goes through the ones that are starred one time and then if there are no more that are featured with the star it won't show anything? Could we make it so that every day it will cycle through a new starred spotlight (we will usually have 3 that are starred, and rotate every day with one of the three features) until we change them to three new spotlights?

**Comment by joelworsham** [comment]
Ah yes, I suppose this bug JacksonCollege/Spotlight#3 has crept back in. I will re-open and that and make sure it gets fixed.
