### ISSUE TITLE
Events not showing up on calendar with that span more than one day and if set to weekly

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#118]
This can wait until after we launch, but Marilynn was putting in some events that aren't populating on the calendar.

-Our mid semester break lasts from Feb. 29 - March 4 and she put that date range in and it's not populating on the calendar

-she also set an event to show up weekly and she checked the "weekly" check box (the men of merit weekly meeting) and that isn't showing up as well.

Thanks!

**Comment by joelworsham** [comment]
Is this happening again?

**Comment by banksashleym** [comment]
Hi Joel,
We are still having an issue with creating one event and designating it as a weekly event. It still does not show up on the calendar? If we create one event and have it span over multiple days it show up, but if we create an event and want it to show up every Wednesday until a specified date it doesn't show up?

**Comment by joelworsham** [comment]
I'll look into this

**Comment by joelworsham** [comment]
There are weekly events on the calendar showing currently, like the Men of Merit Weekly Meeting, for example (which there are 2 events for this currently, not sure if this is intentional).

Can you provide a specific event that is weekly and not showing so I can try to replicate it?

**Comment by banksashleym** [comment]
Absolutely...(I think with the Men of Merit weekly meeting Marilynn has just duplicated the event)

I have created an event "free tax help for student veterans" for March 9 (there are a few other free tax help for veterans events as well but these are at different times). This event will happen starting March 9 and should continue through April 13 as a weekly event.

**Comment by joelworsham** [comment]
All set!
