### ISSUE TITLE
Feature image for 404 page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#119]
Could I also have the option of adding a set feature image to the 404 page as well? I noticed that if there is a broken link, some of the 404 pages have huge images in place where the image is as well...kind of like the search page.

Thank you!

**Comment by brashrebel** [comment]
Ashley can you possibly share an example?

**Comment by banksashleym** [comment]
Yes, absolutely...on the page http://jacksoncollege.staging.wpengine.com/academic-deans/student-assessment/course-level-assessment/ the "official Course Outlines" is a broken link...I'm assuming because I have removed the 2's from the slug? Anyhow, the broken link goes to this page:

http://jacksoncollege.staging.wpengine.com/academic-deans-2/faculty-resources-2/course-outlines/

**Comment by joelworsham** [comment]
Very interesting. I will make sure this gets added / corrected.

**Comment by banksashleym** [comment]
Hello! I see this is closed but the large image on some of the 404 pages are still showing up? 

http://jacksoncollege.staging.wpengine.com/academic-deans-2/faculty-resources-2/course-outlines/

Let me know if I'm just not looking in the right spot :) thanks!

**Comment by joelworsham** [comment]
Yes, the spot is `Settings -> Jackson College : Pages`. I have modified this though so that if NO image is chosen there, no image shows at all.

Sorry for any confusion
