### ISSUE TITLE
Ability to remove three buttons (request info, schedule visit, start app) on certain pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#133]
Dotty is requesting the ability to remove the three buttons (request info, schedule visit, start app) from some of the pages in the left side navigation? We are presenting the new site at the board meeting next week and she doesn't think they necessarily need to be there on the Board of Trustees pages...there are a few other site sections that I would like to remove these as well? Right now they are currently widget buttons that have been added universally to every left hand page.

Let me know if this is possible, thanks!

**Comment by joelworsham** [comment]
There is now an option at the bottom of all widget forms to select site sections that the widget will be hidden from
