### ISSUE TITLE
Logo navigation links

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#14]
I know I asked you to change the text size of the e-services, etc...and the apply, visit, etc...but now they are looking extra small. Sorry! Could we bump these up a point size and then center them vertically so that they fit into the burgundy bar with equal amount of space at the top and bottom? Could we also make the search bar appear a little longer - it seems kind of short in length.

Thanks!

**Comment by joelworsham** [comment]
:+1:

**Comment by joelworsham** [comment]
Just a heads up, I'm going to move the search bar into its own issue, just so we can keep them separated.

**Comment by banksashleym** [comment]
Thanks!
