### ISSUE TITLE
Event overflow issue on calendar

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#140]
If a day has too many events to fit in the calendar day "box", it will simply overflow into below.

**Comment by joelworsham** [comment]
@banksashleym 

Just a heads up, I corrected this, and in doing so realized that the event tooltips would need to be modified in order to do so. So I ended up completely revamping the functionality and interaction of them.

Could you do me a favor and take a look? Let me know if it seems intuitive enough and is easy for you to use. http://jacksoncollege.staging.wpengine.com/events/

Thanks!

**Comment by banksashleym** [comment]
Hi Joel, this looks good to me!

**Comment by joelworsham** [comment]
Perfect, thanks!
