### ISSUE TITLE
New pathway design

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#159]
We need to modify the pathway single page to look like this mockup instead of the current table layout:
![image001](https://cloud.githubusercontent.com/assets/4993131/16235123/b57a9f56-37a1-11e6-834d-af04d8a7a076.jpg)

**Comment by banksashleym** [comment]
This looks good. If the picture could automatically pull from the program page feature image that would be great. But if I could have the option to input the program snippet text I would like that. That way I can control the content and keep it to around two sentences.

**Comment by joelworsham** [comment]
All set and on staging.

For the excerpt, you can now enter that on the Program page itself. If it doesn't show up, click on "Screen Options" at the top right of the screen and check the box next to "Excerpt".

**Comment by banksashleym** [comment]
THIS IS AMAZING! I LOVE IT!
Can you push just this new program section over to the live side without having to copy all of staging over? Or do you take the staging site and copy the whole staging to the live site? Only reason I'm asking is that I've been making some changes to the live and I see they aren't reflected on the staging :)

We are good to go with this, whenever you are ready. I so appreciate you working so quickly to expedite this issue!

**Comment by joelworsham** [comment]
I can push just this to live! I will do so shortly.

**Comment by banksashleym** [comment]
Sweeeeeet :) Really, good job. This is exactly how I envisioned it to look/function.

**Comment by banksashleym** [comment]
Thanks!! Sorry, just noticed that they are in reverse alpha order :( I thought it was how I had them configured in the pathway list where I add the programs, but it autmatically puts them in order from z-a. If we could just reverse so they are in alpha order that would be wonderful :)

**Comment by joelworsham** [comment]
Ohhhh whoops! Sure thing.

**Comment by joelworsham** [comment]
All set

**Comment by joelworsham** [comment]
Why the WordPress default ordering is Descending and not Ascending, I will never know :P

**Comment by banksashleym** [comment]
Good deal, I appreciate it! Sorry, just one more thing with these pathways and I will be done lol. I was looking at the pathway page on my phone last night (vertically) and if we could just have the title/paragraph pop in below the image on the vertical mobile version (horizontally it looks just fine) that would be great!
![img_0926](https://cloud.githubusercontent.com/assets/15264315/17211454/a3e9a30a-5497-11e6-8ff6-3e3aae2b7bc1.PNG)

**Comment by joelworsham** [comment]
Aha yes. Apologies, I was in such a hurry to get this out the door that I forgot to anticipate mobile! I'll adjust that shortly.
