### ISSUE TITLE
News Banner Image functionality

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#20]
_From @banksashleym on December 7, 2015 16:59_

When a visitor click on a news item story and goes to the landing page - could we make the banner image across all of these pages be a static banner image? When I was uploading, the photos worked really well in the more rectangular space on the home page, but on the landing page the photo didn't seem to translate as well..I'm thinking we will use that same featured image from the home page as a photo in the body of the story instead of in the banner.

_Copied from original issue: JacksonCollege/Staff#3_

**Comment by joelworsham** [comment]
Would it help to offer a secondary image uploader where you can set a more rectangular image for the page itself? It's a fairly common technique we've implemented in the past.

**Comment by banksashleym** [comment]
I think that if we could just do one banner photo across all of the news items (and one for alumni/student spotlight as well) that would suffice for now? I'm thinking that whatever photo Marilynn chooses for the feature image that image she will also just insert in the body of the story.

**Comment by joelworsham** [comment]
Okay sure. Do you want me to integrate the featured image into the body content automatically?

**Comment by banksashleym** [comment]
Sure, that would be great!

**Comment by joelworsham** [comment]
Add the image in WP Admin -> News -> Settings

**Comment by banksashleym** [comment]
Great, thanks!
