### ISSUE TITLE
News Title

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#22]
_From @banksashleym on December 7, 2015 17:5_

When someone clicks on the news item and gets to the news story, could we make the burgundy title bar area "Jackson College News" instead of having it reflect the title of the page? It seems a little redundant having it in the burgundy bar as well as the news story main content?

_Copied from original issue: JacksonCollege/Staff#5_

**Comment by joelworsham** [comment]
It doesn't currently show in the news story main content. Do you want it to show in the main story content? It should show somewhere on the page if not in the burgundy bar.

**Comment by banksashleym** [comment]
Yes, I was thinking we would include the title of the story as a header in the main content, or if you want to include the functionality of adding the title of the story/article to the main content that would be at the top of the that would be great! I would also like to implement this type of thing as well with the alumni/student spotlights - where the burgundy bar for each story would just say "alumni spotlight" and then the title of the article would be in the main content of the story.

Thanks!
