### ISSUE TITLE
News archive page and navigation

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#24]
_From @banksashleym on December 7, 2015 17:10_

This is probably a training questions rather than a functionality question, but we would like to categorize the news releases by year..so along the left side we would like a spot for "2015 press releases" which would then bring up a list of the 2015 releases. I did see that we can add categories/tags - so maybe we can cover this topic at our training.

_Copied from original issue: JacksonCollege/Staff#8_

**Comment by joelworsham** [comment]
Sure thing. Where are referring to by "along the left side"?

**Comment by banksashleym** [comment]
Oh, sorry...We would like the "2015 press releases" "2014 press releases" etc.. to be nav links in the left side navigation. Then when a visitor clicks on the 2015 link it would pull the 2015 releases.

Thanks!

**Comment by joelworsham** [comment]
All set. Just go to WP Admin -> Widgets and add the "Archives" widget to the "News" sidebar area.
