### ISSUE TITLE
news items on home page

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#25]
_From @banksashleym on December 7, 2015 17:13_

Is there a way we could pick which news stories we would like to feature in the large top space on the home page, and which we would like for the bottom two smaller spaces? I noticed that how it is, the most recent news item fills the top spot...I think there will be some times where we would like to give precedence to one story over another.

_Copied from original issue: JacksonCollege/Staff#9_

**Comment by joelworsham** [comment]
It's now available in the "Publishing Box" (top right) when editing the News Item.

Default is "Not Featured". "Primary Featured" makes it the big, top item on the home page. "Secondary Featured" makes it one of the 2 smaller, bottom items on the home page.

**Comment by banksashleym** [comment]
Perfect, thanks!!
