### ISSUE TITLE
Program landing page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#28]
I'm sorry do to this, but I had a meeting with Dotty and Marilynn this morning and we would like to re-configure the design of the program landing page if possible. 

Could we have the page re-structured to look like the following?
http://www.jccmi.edu/NewWebsite/index.html

Could there also be the functionality to change the color of the colored bar behind the "How to get started" etc..We would like to develop a color scheme for each pathway, and for those programs under a certain pathway we would like to change the color of the colored bar...for example, in the business pathway, all the programs will have a blue bars, for health sciences the colored bars will be green.

Thanks!!

**Comment by joelworsham** [comment]
All set. For better back-end support, the image upload position has moved. It is now to the right and will need to be re-set for any programs you have already added.

**Comment by joelworsham** [comment]
Also, just a heads up, each section is now controlled dynamically with a repeater field, this way you can exclude or add various sections as you need.
