### ISSUE TITLE
Side navigation for grandchild pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#33]
I have some pages that are children of children pages...for example "Information Technology" is a parent page> "For Employees" is a child page> and there are many child pages under the "for employees" tab. Right now only the "For employees" side navigation link is showing up. Would it be possible for those side nav's that have child pages, including an arrow on the side of those nav links, that when clicked on, will populate the grand child pages? Sort of like what we have on our current website?

An example: http://www.jccmi.edu/studentservices/admissions/

**Comment by joelworsham** [comment]
Just a heads up, I went to this page: http://jacksoncollege.staging.wpengine.com/academics/ and noticed it wasn't using the "Post Children" widget, but rather the "Custom Menu" widget.

Perhaps this is intentional, but for now I added below the menu the post children widget so you can see how this dropdown works.

Also, just so I can better understand how this is working out for you, why are you using the "Custom Menu" widget there?

**Comment by banksashleym** [comment]
Oh sorry, I didn't know which widget to use...I am liking how the custom menu option is working however...I need to be able to add custom links for each side nav that also link to outside urls or pdfs and not just use child pages. And I also need to be able to have more control over which child pages show up. For instance, Financial Aid has a lot of child pages that I don't need to have in the side navigation. Could we style the custom menus to to have the same style?

**Comment by joelworsham** [comment]
Hmmmmmmmmm. Yes I can style the custom menu, and I will, but I'd also like to solve the dilemma of not being able to use auto-populated menus.

Would it be helpful if I added some options to the Post Children widget to eliminate specific children from the widget? As for custom links, I suppose the only way is to use a custom menu in conjunction with the post children widget, though the downside would be interpolating the post children menu items with the custom menu items.

**Comment by joelworsham** [comment]
Alrighty, all styled (make sure to refresh). You can also see that when a Custom Menu is butted up against a Post Children widget, the "connection" is seamless. Perhaps this would help you out for if you ever need to use both.

**Comment by banksashleym** [comment]
Sure, we can do that, and I like the feature of auto populated menus but I think we just have so many exceptions that for now it might be easier to set up using custom menus? For instance, there are many sections that that will need to link to other sections...Student Services doesn't necessarily have a lot of child pages, but I will need the student services side navigation to have links to Financial Aid, Admissions (and only parent page, not any of the child pages). With a custom nav for student services I am able to do that...not sure how we would do that with auto populated? It seems that if we are adding so many options to the Post Children widget I am still having to go in an manually edit the nav items anyway?

It's hard because a lot of our content overlaps between "sections" and I will need to link that information. For example, the policies page is a child page under Institutional Research, however it's the President's office is also involved in the policy change process - so he likes to have a link to the policies. With an automated menu, the policies page will not show up in the President's section side-menu. In addition, the President also likes to have a link to the Board of Trustees section (but not necessarily all of the child pages?)

Would it help if in those sections where it's pretty cut and dry to apply the Post Children widget, and on those sections where it pulls different sections and uses custom nav links to apply the custom menu widget?

**Comment by joelworsham** [comment]
@banksashleym Question. Which would be more useful to you:

1. When editing a page, there is a checkbox "Exclude from menus", and that page would never show in **any** menu anywhere (including the sidebar) that is auto-populated.
2. OR When creating a sidebar menu, it is possible to exclude specific pages from it there.

**Comment by joelworsham** [comment]
Hmmmmm okay. I'll let it be for now. We should consider things like this as an opportunity for different content organization strategies though. Perhaps we can talk about some things like this sometime with @brashrebel

**Comment by banksashleym** [comment]
Yes I agree. Kyle and I talked a little about this yesterday. I think once we launch and I have the time I'm going to sit down and work through the content so that it will be more streamlined with automatic menus.

**Comment by joelworsham** [comment]
Great!

**Comment by banksashleym** [comment]
Thanks for all of your help and tips! While I feel that we cut down on a lot of unnecessary content with migrating things over, I think the next steps are to re-structure and find the problem areas!

**Comment by joelworsham** [comment]
For sure. I've been very happy with the site progress and with your ability to slim down as much as you have. So thank **YOU** for all the work you've done on this as well.

:+1:

**Comment by banksashleym** [comment]
Thanks!

Sorry, one more question about the side menus...I am going to try and incorporate the majority of sections with the Post Children widget, but is there a way that we could customize the link text? 

For instance, we have a lot of "hours" pages...there is a page "Central Campus hours" "Maher Campus hours" "Student Services hours" and in order to keep track of them in the pages list I have had to name them that way so we don't have 6 "hours" pages. But when I am in the Maher Campus section, the side nav link doesn't necessarily have to say "Maher Campus hours" but just "hours".

Just a thought...I can do this with the custom menus as well until I can re-structure the content :)

**Comment by joelworsham** [comment]
Hmmm, let's go ahead and keep using custom menus for that for now if that's okay.

**Comment by banksashleym** [comment]
Sounds good to me, thanks!

**Comment by banksashleym** [comment]
Just noticed that the child pages are not linking to any pages in the custom side menu. For example on the Academic Deans pages (http://jacksoncollege.staging.wpengine.com/academic-deans-2/?preview=true&preview_id=3181&preview_nonce=cc1305a5ae) the Student Assessment is a parent page with content, and there are also  4 or 5 child pages that aren't linking to any content. 

Thanks!

**Comment by joelworsham** [comment]
Right, the child pages in the dropdown not linking is definitely a bug, but as for the dropdown parent page, I simply copied what was on the current jccmi site. I will refine it to make it clickable. Having something that, when clicked, does on page actions, but then also links somewhere is always a sticky situation. I'll see what I can come up with.

**Comment by banksashleym** [comment]
Ok, sounds good...would you like me to configure it so that the parent page is blank, and then I just copy the information from the parent page onto a new child page? If that makes it easier on you and think it would make a better user experience I can definitely do that. I wasn't sure what the protocol or norm was, so i just copied the landing page information into the parent page.

**Comment by joelworsham** [comment]
I'd say the hierarchy you have going is going to be better the way it is now. The menu situation, I believe, shouldn't dictate the content structure. I'll figure out a good way to make this work :)

**Comment by joelworsham** [comment]
I think a good protocol may be for you to add the parent page twice. Add it once at the top level, like you did, place the children under it, and then place the parent in there AGAIN at the top, probably with slightly different wording. So in the Academic Deans example, your menu might look like this:

Academic Deans
Adjunct Resources
Faculty Resources
Guided Pathways
Student Assessment
    Student Assessment Home (<- or something like that. It is the same page as the parent)
    Course Level Assessment
    Course Review
    Program/Discipline Review
    General Education ADO
Student Resources
Syllabi

**Comment by joelworsham** [comment]
Feel free to re-open this if you feel that it's still not to your liking

**Comment by banksashleym** [comment]
That works for me, thanks!!

**Comment by joelworsham** [comment]
:+1:

**Comment by joelworsham** [comment]
@banksashleym Did you mean to re-open this?

**Comment by banksashleym** [comment]
Oops, yes, but it looks like I didn't save my comment!

http://jacksoncollege.staging.wpengine.com/academic-deans-2/student-assessment/?preview_id=5037&preview_nonce=8681df2d02&preview=true

When I make the custom menu and the first child the same menu item (in this case the parent page is "Student Assessment" and I also placed that same page in the first child spot and called it "About Student Assessment") - Would it be possible to keep the nav open and that first child bold when clicked so that visitors would know they are in the student assessment section? I believe it's assuming that that first page child page is essentially the parent page so it's automatically closing the child nav menu and making the tab bold.

Let me know if that doesn't make sense lol

**Comment by banksashleym** [comment]
Yes, but for some reason it isn't saving my comment!

**Comment by banksashleym** [comment]
Oh there it goes :)

**Comment by joelworsham** [comment]
Ah yes I see. It does to that (except for the parent being bold) for child pages, but it is not doing that for the parent/child page. I will fix this.
