### ISSUE TITLE
Insert ability to use tabs

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#46]
Would there be a way to add some funcitonality to do tabs on a page? There are many pages on our current site that uses tabs and I think it would be nice to keep that sort of functionality.

http://www.jccmi.edu/academics/academic_calendar.htm

Thanks!

**Comment by joelworsham** [comment]
You can see an example of it here: http://jacksoncollege.staging.wpengine.com/tabs-test/

It uses shortcodes. So the format is:

```
[tab]
[tab_section title="Tab Title"]
Tab Content
[/tab_section]
*repeat as many sections as needed*
[/tab]
```

Feel free to delete the page when done.
