### ISSUE TITLE
Default page template to not show events

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#48]
Could we re-configure the default page template so that the events don't show up on every page in the right most column? I would like the content to fill up all the columns on the default template, and then maybe create a few more page templates where we could incorporate events only to certain pages? I will create a separate issue for that. Could we even configure the news/spotlight areas to just have the content fill all columns instead of showing events too? I didn't see an area where I could change the page template of those certain areas?

Thanks!

**Comment by joelworsham** [comment]
Right. I can switch things around so that the Default Template does not have the right sidebar, and then create a separate template to incorporate that right sidebar, but keep in mind that any page you have using Default Template will be affected.

**Comment by joelworsham** [comment]
It does appear that news/spotlight areas are currently not showing events actually. I've swapped the templates.

The page template for having that sidebar is now called **"Right Sidebar"**.
