### ISSUE TITLE
Events page template

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#49]
I think this is more of a question than an issue...is there a way to create an events page template, and specify which events show up in for certain pages or sections? For instance, when creating events, I see that we can put them into categories, types and tag them as well? 

I'm not sure how I would do this, but is there a way for instance, to create a page template for events (how the default page template is set up now with the right most column pulling from the events field) and only specifying certain events? Like Student Life puts on a lot of student based events that I don't necessarily think we need to have on every page, but it would nice to be able to display those events just in the student life section along the right side...would this be done using a "type" or "category" of events and only having the student life section pull that type or category?

Thanks for your help!

**Comment by joelworsham** [comment]
Hmmm that's a good question. Right now that right sidebar is accessible from the "Page Right" sidebar, but that, obviously, only provides control over EVERY page with that sidebar. I will probably come up with a way to have a little more control over that sidebar so you can have more control of what shows up. It *probably* won't be a page template, but I'll have to figure out is going to work best.

**Comment by joelworsham** [comment]
I've added a new field to the "Events" widget for filtering through a category if needed. I think this in conjunction with everything else should allow you to do this.

If not, feel free to re-open.
