### ISSUE TITLE
Page templates question

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#50]
This is more of a question rather than an issue...When I get back to work on the 4th, I would like to spend a little bit of time prettying up the most important top-level pages, and have some flexibility with the page templates. Like for some pages I would like to add images/buttons down along that right-most column...or for some pages I would like the text content to go across the whole page at the top, and then maybe do a row of two or four photos in the columns below that...is this possible with just one blank page template, or should I come up with some mock-ups and create specific templates for each look? I'm thinking maybe 3 different configurations at max.

And then the second part of this question - I see that there is already a page template for "two-column" but I'm not really sure how to place content in each column? When I click on the two column page template and preview changes it just flows the content across the whole main content area.

Thanks!

**Comment by joelworsham** [comment]
Whether or not more templates should be created depends on the nature of the requirement. I would probably say they should be templates, so they are re-usable and effective. But there are a number of things that you are able to do without templates, such as buttons, images, carousels, tabs, tables, etc.

For anything layout (like rows and columns), a page layout is *usually* better.

As for the Two Column template, that might be a big confusing. What it refers to is the sidebar being one column and the content being the second, whereas the Default Template has three (sidebar left, content, sidebar right). I can re-name that if you like to be a little more clear.

**Comment by joelworsham** [comment]
I think you should be able to accomplish most of this now. Feel free to re-open if you can't.

EG: For the right sidebar, you can have a unique section right sidebar with custom widgets

If you need any specific layout-based page templates, feel free to let me know! There actually aren't very many as it is now.
