### ISSUE TITLE
Content Grid page template - content grid link option not pulling all pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#52]
I am working on the academics parent page, and would like to implement the content grid page template. When I add a new content grid and try to link that to a page, only about 5 page options are showing up in the list, not the whole list of pages.

In this instance I need to be able to link it to our programs of study, but I would like the ability to be able to link it to academics content as well as pages.

Thanks!

**Comment by joelworsham** [comment]
Sorry about that. Was a nasty little bug!

**Comment by banksashleym** [comment]
Sorry, this seems to still be acting a little weird! I am now able to view the list of pages in the dashboard, but when I preview the page and actually click on the link it still doesn't go anywhere?

Like right now I have added the link "programs of study" to the programs of study content box, but when I preview and click on the link the url changes from "http://jacksoncollege.staging.wpengine.com/academics/" to "http://jacksoncollege.staging.wpengine.com/academics/3257/"

**Comment by joelworsham** [comment]
Sorry for the inconvenience. It's working now.
