### ISSUE TITLE
Landing grid images added to regular page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#53]
I am working on the academic landing page and would like to be able to add the look of the "landing grid" page template images (the images with the solid band at the bottom and then you hover over and more information pops up - like on the future students page http://jacksoncollege.staging.wpengine.com/future-students-2/?preview=true&preview_id=4240&preview_nonce=94bc7541a3) but I still need the left navigation to be present. So on the academics page, instead of the content grid boxes, I would like these to work more like the landing grid boxes.

I guess what I'm trying to say - is it possible to just drag that image/button functionality of the landing grid onto the current academics page that uses the default template, or will a new page template have to be created in order for me to be able to do this?

Thanks!

**Comment by joelworsham** [comment]
I'm going to make a fairly large adjustment. In light of new needs and such (which is not a problem), I'm going to make the sidebar controls independent of the page template. This will allow some flexibility in layout. While I'm at it, I'm also going to remove the "Archive" templates and simply create a shortcode for those.

NOTE: This will require some adjustment on the site. All archive pages will need to have the shortcodes added (I will detail once I'm done what those shortcodes are), and various pages will need some sidebar adjustments. I will make the default sidebar settings to be show the left and hide the right.

**Comment by joelworsham** [comment]
Alrighty. BIG changes have been made to the theme to accommodate flexibility. I won't go into all of them, but basically there are three things to be aware of now.

1. Sidebar controls are **independent** of the page template now. *Every* single public post, page, event, etc has a sidebar control panel at the bottom of the edit screen. You can select left sidebar, right sidebar, both, or none. There have been some defaults setup. For instance, the global default is only a left sidebar; whereas if you go to News -> Settings you see you can set the setting "News Default Sidebars", which is now set to "both".

2. Archives have been dramatically altered. They are no longer page templates. There are 2 ways to control archives now. The primary way is to go to Settings -> Jackson College -> (tab) Pages. Here you see a few pages. Some are archives, and some are not. For example, Site Index is not an archive per-say, but Jobs For Jets is. This is how you "attach" an archive view to a specific page, and then use that page controls to alter the title, section it belongs to, and everything else, like before. The archive will now simply be attached to the bottom of the content. The second way to use an archive is through a shortcode. You use it like such `[archive_staff]`. Any content type that has a taxonomy can be filtered with the shortcode by using the term slug (which can be found on the taxonomy list page). For example `[archive_staff department="admissions"]`. I recommend only using this shortcode for edge cases and to rely on using the "attaching" method instead. Also, there are some taxonomies that have "taxonomy page" available. For example, the staff department pages are like `/staff-department/admissions/`. As of now, this does not exist for all content types, but it can and probably will in the future.

I believe that's it for now! I know this is a lot to take in. Let me know if you have questions

NOTE: This will probably require you to go through some pages and make sure are configured properly with the sidebar and page templates.

**Comment by banksashleym** [comment]
Awesome, this is great! 

One question - I see that I can change the default page layout for a section in the settings (like the news settings), but for a specific page, say when I scroll down and find the page layouts and when I click on the full with template, it will let me hover over that one, but it won't let me select it? Is there somewhere else where i'm able to select the page template for a specific page?

Thanks!

**Comment by joelworsham** [comment]
I don't quite understand. You say "when I scroll down and find the page layouts and when I click on the full with template, it will let me hover over that one, but it won't let me select it". Do you mean the sidebar? You're trying to select the sidebar settings?

I am able to select the sidebar setting for pages. What exactly is the issue you're experiencing?

**Comment by banksashleym** [comment]
Yes, sorry, I'm trying to select a different sidebar setting. For instance, I would like the locations page to be the full width, however in the dashboard when I go to the locations page and scroll down I am able to hover over the full width sidebar option and it turns purple, but it won't let me select it. The default left sidebar remains selected.

**Comment by joelworsham** [comment]
Huh, that is odd... Let me look into this.

**Comment by joelworsham** [comment]
Hmmm I was able to select full width, update it, and have the page become full width.

What happens when you click on a different sidebar setting?

**Comment by joelworsham** [comment]
Try going back to the "Locations" page edit screen, and then once on it, manually do a page refresh.

**Comment by banksashleym** [comment]
Re-opening this issue just to get it back in the list. (about not being able to select a different sidebar setting.)

Thanks!

**Comment by joelworsham** [comment]
Did you try doing a manual page refresh? Is it still not working for you?

**Comment by banksashleym** [comment]
Weird...I did a manual refresh and cleared all cookies/browsing data and it still won't work in Chrome or Explorer, but I am able to make the selection in Firefox, lol

**Comment by joelworsham** [comment]
Huh, very odd. I'll look into this.

**Comment by banksashleym** [comment]
Very weird! I tried Safari too and that won't work as well...

Also, have you been able to get into the widget area? I still cannot open that either - it will just go to a blank screen.

**Comment by joelworsham** [comment]
As for the widgets, yes I need to delete the obsolete widgets we were using. I wanted to wait until we verified the custom menu attaching to a site section was going to work. I'll make sure to get that working ASAP

**Comment by joelworsham** [comment]
I'm struggling to replicate this issue. Are you familiar with chrome dev tools? Can you open them, and then open the console, and then reload the page and try again? See if any javascript errors show up in the console.

Just in case you don't know how Ctrl + Shift + J will bring up dev tools with the console open.

**Comment by banksashleym** [comment]
Sure thing - it's saying:
https://cloud.githubusercontent.com/assets/15264315/12306328/2f3ec33a-ba07-11e5-8c3c-dea97ea4818b.jpg

**Comment by joelworsham** [comment]
Thanks for that! Can you try reloading the page and see if the problem still persists?

**Comment by joelworsham** [comment]
@banksashleym Any updates on this?

**Comment by banksashleym** [comment]
Sorry, i was out sick yesterday. I just checked in Chrome and this is now working!

**Comment by joelworsham** [comment]
Oh no worries! Hope you're feeling better.

Glad to hear it's working!
