### ISSUE TITLE
Student success navigators should not be a table

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#69]
On [this page](http://jacksoncollege.staging.wpengine.com/academics/academic-advising/) there's an HTML table used to render the student success navigators. I'm sure this is just carried over from the old site but should be addressed. Tables are _very_ difficult to make responsive and are really only meant to be used when displaying actual tables of data and never for layout like this.

Not sure if we have a shortcode for outputting a grid of staff or whether the column shortcodes need to be used here. If there are other parts of the site that need similar content displayed this way, we should probably have a shortcode for outputting this layout and selecting the content type. Just an additional consideration.

**Comment by joelworsham** [comment]
There are column shortcodes now. Discussed here #58 

I do like the idea of a grid of staff being a shortcode. @banksashleym Are those people staff? Do they exist in the Staff section of the site now? Also, does that particular set of staff belong to a department?

There is an `[archive_staff]` shortcode currently. I could allow an alternate display setting for a grid like that. Something like `[archive_staff display="grid"]`. Also, if that particular group is not a department, I could add an "include" parameter to include staff by their ID directly, like so: `[archive_staff include="1,67,10,39"]` (those ID's are arbitrary).

@banksashleym Thoughts?

**Comment by brashrebel** [comment]
I really, really like this idea. Not only does it fix the layout problem but, if a department or some other factor is specified, it also makes this list dynamic. So when anything about those staff changes (new person added, name change, email change, picture changes, etc.) this grid will instantly reflect those changes as well. Two huge wins.

**Comment by banksashleym** [comment]
Yes, I absolutely love this idea! Thanks so much! There are a few other areas in the site that would benefit from this treatment as well....awesome idea!

**Comment by brashrebel** [comment]
Created a separate issue for making this shortcode. Close this issue when this table has actually been replaced with the new shortcode.

**Comment by banksashleym** [comment]
This is perfect! Is this the way I should incorporate the different department staff as well? Like create a Marketing Contact page and include the shortcode that specifies a department? Or should I use the department widgets functionality and include that in the menu like how you showed me on Wednesday? Sorry, I am getting everything confused!! :)

**Comment by banksashleym** [comment]
Sorry, I spoke too soon. I just added the shortcode to the staff page with department="(name)" and it works beautifully! thank you so much!

I guess just one other question I have is - could we make the image size a little smaller? When I sized the images, I sized them to be a little bigger, just in case we needed them anywhere else on the website. But could we make the container for the staff directory images maybe half the size?

**Comment by banksashleym** [comment]
Also, could I have the ability on on a staff member to be able to add them to multiple departments? For instance, Christie Hughes is a faculty member for Graphic Design and also 3D Design & Animation, however I can only add her to one department. Could we do a check mark box instead of only being able to select one department?

Thanks!

**Comment by joelworsham** [comment]
Ahhh yes, sure thing.

**Comment by joelworsham** [comment]
/JacksonCollege/Staff#30

**Comment by joelworsham** [comment]
@banksashleym FYI, I closed this because it looks like you've replaced the table successfully (thanks!) and also the last request you had here I've moved to the issue linked above.
