### ISSUE TITLE
Academic advising - remove inline styles

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#70]
Also on [this page](http://jacksoncollege.staging.wpengine.com/academics/academic-advising/) there are some elements under the student success navigators which have inline styling applied that makes the two columns overlap on narrower screens. Very broken experience. This should probably be converted to the new shortcode method at least.

**Comment by banksashleym** [comment]
Good deal, Joel and I talked yesterday about all of the styling that was brought over from the old site...he was able to provide me with a shortcode to create rows/columns, which will be so helpful!

**Comment by brashrebel** [comment]
Yes, that will allow us to more easily handle the adjustments for different screen sizes and make things a little better for you than just HTML styles. Still, I think those should probably be used more for the edge cases. If there are instances of consistent layouts being used with similar types of content, all our lives could be made easier by generating shortcodes more tailored to those use cases. Just something to think about.
