### ISSUE TITLE
Custom links in side menus pointing to localhost

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#74]
Not sure how many occurrences of this there are or how they ended up this way, but I encountered some menus using "Custom Link" with URLs that point to a local install of WordPress. This means they are pointing to a non-public URL and are inaccessible to anyone besides the person who added the links.

Example: on the "Campus View Handbook" menu there are two custom links to PDF files located at:
`http://127.0.0.1:8080/wordpress/wp-content/uploads/2015/12/*.pdf`

FYI, 127.0.0.1 is an IP address that is universally used for pointing to `localhost` which means "this machine". It is never publicly accessible. These files will need to be uploaded to the site and the URLs will need to be corrected. Additionally, it is also probably possible to link to the media item instead of the file's static URL as this would be more dynamic.

**Comment by banksashleym** [comment]
Gotcha, thanks for catching that. That must have snuck over from when I was working on the local install on my computer. I had created all of these custom nav menus on my local version, and when I found out I could do custom menus on the staging site I had both windows open and just copied and pasted the URL. I will go through the menu's and make sure these are uploaded to the staging. Thanks!

**Comment by joelworsham** [comment]
I can do a DB search / replace to eliminate definitively all instances of `http://127.0.0.1:8080/wordpress` if need be.

Also, @banksashleym, just so you know, it is better when doing **any** internal linking to not use anything except for the URI. So for that link, it would have been better to do `/wp-content/uploads/2015/12/*.pdf`.

The browser will always auto-fill in the current site and doing it this way ensures that no matter what the domain is, it will always work.
