### ISSUE TITLE
Request info button goes nowhere

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#77]
I may have missed why but the big Request Info button in the sidebar has no URL to point to. I'm assuming no one's gotten to this yet but regardless, logging to ensure it isn't forgotten.

**Comment by banksashleym** [comment]
Yes, I have created a page for all three of the buttons "Request More Information" "Start Your Application" and "Request a Campus Visit" and instead of linking to the URL I would like to link to the page, however all three are not showing up in the page list?

**Comment by brashrebel** [comment]
@joelworsham do you know why?

**Comment by joelworsham** [comment]
Huh, I will look into this.

**Comment by joelworsham** [comment]
It sounds silly, but it's because there was a whitespace character preceding the custom link on the button. Of course this should *not* break the button. I've made sure to account for this.

Just in case @brashrebel is curios, I just used `trim()`.
