### ISSUE TITLE
New post type for featured stories

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Primary-Theme#81]
We need to make a new content type for publishing the featured content on the site which will primarily be populating the hero image section of the home page and will allow marketing to promote specific things.

What the name of this content type is remains TBD. Ashley will get back with us on whether "featured stories" will be used or something different.

**Comment by joelworsham** [comment]
@banksashleym What do you think? Should we use "featured story"? Keep in mind it's a fairly difficult process to change the name further down the road.

**Comment by banksashleym** [comment]
Marilynn and I are going to see what other colleges are calling this - we will get back to you on this one.!

**Comment by joelworsham** [comment]
:+1: I'll hold off until then

**Comment by banksashleym** [comment]
Ok, so Marilynn and Dotty spoke and they would like to call it "College Spotlight" since they aren't really stories, but basically pulling things that we want to hightlight.

**Comment by joelworsham** [comment]
Great! So it would probably make the most sense to just call it "Spotlight", from an admin point of view anyways. We can always add the word "College" in various template scenarios.

**Comment by banksashleym** [comment]
Good deal, sounds good to me!

**Comment by banksashleym** [comment]
Hi Joel,
I don't see a new tab for "Spotlight" on the left side in the dashboard...is there somewhere else I would go to add these spotlight stories?

Thanks!

**Comment by joelworsham** [comment]
Sorry about that, just realized the plugin wasn't activated on the staging site yet.

All set.
