### ISSUE TITLE
Edit Image: crop/scale tool not working

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#82]
The crop/scale options in the edit image are doesn't seem to be working...when i try to scale an image I get "NaN" in the field...this isn't a big issue because I would rather crop in Photoshop anyway, but I thought I would add it here just so you're aware.

Thanks!

**Comment by joelworsham** [comment]
Interesting, I was able to scale.

Can you provide a few more details so I can accurately replicate your process?

- Which image are you trying to scale?
- What are you trying to change the dimensions to?

**Comment by banksashleym** [comment]
Ok, never mind - it seems to be working now! That's weird...I would select the area on the image and then click the crop button and nothing would happen. And then whenever i would change the number in the Scale fields they would all turn to NaN.

Oh well, works now!

**Comment by joelworsham** [comment]
Very odd! Glad it's working now. If it does come up again and it is a problem for you, don't hesitate to open this back up!
