### ISSUE TITLE
News Archive page styling

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#85]
On the news archives page, would it be possible to:

-add the date published to the visible area - so say I select "december 2015" from the drop down list - it would list the title, date, description and read more button.
-change the header to an H3 or H4 header - these seem kind of big
-remove the page title from the top of the left side nav so that all we see is the news archives widget?

http://jacksoncollege.staging.wpengine.com/2015/12/

**Comment by joelworsham** [comment]
Yup I can do all of that! Just FYI, I'll change the styling of the H1 to make it smaller, but I will leave it as an H1, as it helps SEO to use header tags as a method of showing importance, rather than based on styles. Just so you know :)

**Comment by joelworsham** [comment]
Also, FYI, I've created this pagehttp://jacksoncollege.staging.wpengine.com/news/ and set that to the "news index" page. It's linked from the homepage where it says "JACKSON COLLEGE NEWS"
