### ISSUE TITLE
Hero image spotlight not updating

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#90]
Good morning! We are just about to send the test link out to our department heads...Dotty wanted to change out the hero/spotlight story on the front page (we have corrections, nursing and business as the three we are going to rotate). It was set to corrections, but we want to make business run first. However, when I make business the latest published and change that one to featured, it still shows up with corrections? I removed the feature star from the other two and corrections is still showing up. I refreshed a few times and nothing seems to be happening.

Thanks for your help!

**Comment by joelworsham** [comment]
Right, so once a spotlight is "chosen" for the homepage, the website will refuse to even look for a new one until the next day at noon. There is a button on the home page edit screen on the right side called "Flush Spotlights". Clicking this will do a hard refresh. I've clicked it just now to reset it.

**Comment by banksashleym** [comment]
Good morning! We still seem to have an issue with the hero image not updating/switching stories? I'm wondering if the issue lies with the timing and when they are supposed to switch something happens? It usually occurs sometime in the night...

Thanks!

**Comment by banksashleym** [comment]
You can disregard the above message, I didn't see your comment about the flush spotlights step. It's working now, thanks!
