### ISSUE TITLE
Enhancement on mobile view

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#91]
Del just brought up a point on the mobile site home page. When you are scrolling down the page through the personas on the home page and you just want to scroll and not necessarily tap on any of the personas they will open (which is ok if you mean to click on them, but just for scrolling down it may seem confusing if all of these boxes start to open?) Is there a way to not have them open on a short "tap" but when they intentionally click on the link they personas box would open?

a good example is on http://www.methodist.edu/ where we got the idea for these tabs...on the mobile version they don't open as you are scrolling through, but when you stop to click on the link the persona will change.

Thanks!

**Comment by joelworsham** [comment]
Sure thing. Good point.
